import * as path from 'path';
import { Duration, RemovalPolicy, Stack, StackProps, CfnOutput, Tags } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as ecsPatterns from 'aws-cdk-lib/aws-ecs-patterns';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as wafv2 from 'aws-cdk-lib/aws-wafv2';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as route53 from 'aws-cdk-lib/aws-route53';
import * as route53targets from 'aws-cdk-lib/aws-route53-targets';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';

export interface DeckStackProps extends StackProps {
  /** Public domain the frontend is served on, e.g. deck.01ai.ai */
  domainName: string;
  /** Route 53 hosted zone name that already exists for the apex, e.g. 01ai.ai */
  hostedZoneName: string;
  /**
   * Only true once the 01ai.ai hosted zone actually lives in THIS account and
   * you're ready to point deck.01ai.ai at CloudFront. Leave false for a first
   * deploy so the stack stands up cleanly on the default *.cloudfront.net /
   * *.elb.amazonaws.com endpoints while DNS/cert questions get sorted out.
   */
  enableDns: boolean;
  /** deploy environment label, used in resource names/tags only */
  envName: string;
}

/**
 * Phase-1 stack for the Launch Dossier's AWS architecture (Section 05):
 *   CloudFront + WAF -> S3 (Vite dist/) for the frontend
 *   CloudFront + WAF -> ALB -> Fargate (01Evolve / FastAPI) for the API
 *   RDS Postgres (single instance) + Secrets Manager for app/DB secrets
 *
 * Deliberately NOT included yet (Section 05's "phase 2" — add when traffic
 * actually demands it, per the dossier):
 *   - Fargate autoscaling beyond the fixed desiredCount below
 *   - An RDS read replica
 *   - Multi-AZ RDS (flip `multiAz: true` below once this is past beta)
 */
export class DeckStack extends Stack {
  constructor(scope: Construct, id: string, props: DeckStackProps) {
    super(scope, id, props);

    Tags.of(this).add('project', '01deck');
    Tags.of(this).add('env', props.envName);

    // ---------------------------------------------------------------------
    // Networking
    // ---------------------------------------------------------------------
    const vpc = new ec2.Vpc(this, 'DeckVpc', {
      maxAzs: 2,
      natGateways: 1, // one NAT is enough for phase 1; the private-subnet Fargate
      // tasks and nothing else need outbound internet (e.g. calling OPENAI_BASE_URL)
      subnetConfiguration: [
        { name: 'public', subnetType: ec2.SubnetType.PUBLIC, cidrMask: 24 },
        { name: 'private-app', subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS, cidrMask: 24 },
        { name: 'isolated-db', subnetType: ec2.SubnetType.PRIVATE_ISOLATED, cidrMask: 24 },
      ],
    });

    // ---------------------------------------------------------------------
    // Secrets — DB credentials are auto-generated by RDS below.
    // App secrets are created empty; fill them in via the CLI/console after
    // first deploy (`aws secretsmanager put-secret-value ...`) rather than
    // ever putting real values in this file or in chat.
    // ---------------------------------------------------------------------
    const appSecrets = new secretsmanager.Secret(this, 'AppSecrets', {
      secretName: `01deck/${props.envName}/app`,
      description:
        '01Evolve app secrets: BETA_ACCESS_TOKEN, 01DECK_SESSION_SECRET, OPENAI_API_KEY. ' +
        'Populate real values post-deploy — this construct only reserves the secret and ' +
        'seeds random placeholders for the two token fields.',
      generateSecretString: {
        secretStringTemplate: JSON.stringify({ OPENAI_API_KEY: 'REPLACE_ME' }),
        generateStringKey: 'BETA_ACCESS_TOKEN',
        excludePunctuation: true,
        passwordLength: 40,
      },
    });

    // A second generated secret purely for the session secret, so rotating one
    // doesn't require regenerating the other.
    const sessionSecret = new secretsmanager.Secret(this, 'SessionSecret', {
      secretName: `01deck/${props.envName}/session-secret`,
      generateSecretString: { excludePunctuation: true, passwordLength: 48 },
    });

    // ---------------------------------------------------------------------
    // Database — RDS Postgres, replacing 01Evolve's current SQLite file per
    // BETA_DEPLOYMENT_CHECKLIST.md's own "nice-to-have before wider release."
    // ---------------------------------------------------------------------
    const dbCredentials = rds.Credentials.fromGeneratedSecret('deckapp', {
      secretName: `01deck/${props.envName}/db-credentials`,
    });

    const db = new rds.DatabaseInstance(this, 'DeckDatabase', {
      engine: rds.DatabaseInstanceEngine.postgres({ version: rds.PostgresEngineVersion.VER_16 }),
      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T4G, ec2.InstanceSize.MICRO),
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      credentials: dbCredentials,
      // RDS requires the DB name start with a letter — '01evolve' fails that,
      // and DB_NAME is read back dynamically from the generated secret's
      // `dbname` field below, so nothing else hardcodes this string.
      databaseName: 'evolve01',
      allocatedStorage: 20,
      maxAllocatedStorage: 100, // storage autoscaling — cheap insurance against a launch spike
      storageEncrypted: true, // encryption at rest with the default AWS-managed KMS key -- cdk diff's
      // CloudFormation Validate check (W9008) flagged this as unset; there's no reason not to have it on
      multiAz: false, // flip to true once past beta; phase-1 read replica is a config change, not a rebuild
      removalPolicy: RemovalPolicy.SNAPSHOT,
      deleteAutomatedBackups: false,
      // 7 days hit "backup retention period exceeds the maximum available to
      // free tier customers" on this account — 1 day is the free-tier ceiling.
      // Raise this once the account is off free tier.
      backupRetention: Duration.days(1),
    });

    // ---------------------------------------------------------------------
    // Backend — 01Evolve (FastAPI) on Fargate behind an ALB.
    // Builds straight from the existing 01Evolve/Dockerfile — nothing new to
    // write there, it already listens on $PORT (defaults to 8080).
    // ---------------------------------------------------------------------
    const cluster = new ecs.Cluster(this, 'DeckCluster', { vpc, containerInsights: true });

    const apiLogGroup = new logs.LogGroup(this, 'ApiLogGroup', {
      logGroupName: `/01deck/${props.envName}/01evolve`,
      retention: logs.RetentionDays.ONE_MONTH,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    const api = new ecsPatterns.ApplicationLoadBalancedFargateService(this, 'ApiService', {
      cluster,
      cpu: 512,
      memoryLimitMiB: 1024,
      desiredCount: 2, // two tasks across AZs from day one — cheap insurance, no single point of failure
      publicLoadBalancer: true,
      taskImageOptions: {
        // 01Evolve/Dockerfile already exists in the repo — build from it as-is.
        image: ecs.ContainerImage.fromAsset(path.join(__dirname, '..', '..', '..', '01Evolve')),
        containerPort: 8080,
        logDriver: ecs.LogDrivers.awsLogs({ streamPrefix: '01evolve', logGroup: apiLogGroup }),
        environment: {
          // Non-secret config. Matches BETA_DEPLOYMENT_CHECKLIST.md's documented env vars,
          // EXCEPT 01DECK_ALLOWED_HOSTS -- see the addEnvironment() call right after this
          // construct, which is why that one isn't set here.
          '01DECK_ALLOWED_ORIGINS': `https://${props.domainName}`,
          '01DECK_SECURE_COOKIE': 'true',
          OPENAI_BASE_URL: 'https://api.openai.com/v1',
          OPENAI_MODEL: 'gpt-4.1-mini',
        },
        secrets: {
          OPENAI_API_KEY: ecs.Secret.fromSecretsManager(appSecrets, 'OPENAI_API_KEY'),
          BETA_ACCESS_TOKEN: ecs.Secret.fromSecretsManager(appSecrets, 'BETA_ACCESS_TOKEN'),
          '01DECK_SESSION_SECRET': ecs.Secret.fromSecretsManager(sessionSecret),
          DB_HOST: ecs.Secret.fromSecretsManager(db.secret!, 'host'),
          DB_PORT: ecs.Secret.fromSecretsManager(db.secret!, 'port'),
          DB_USER: ecs.Secret.fromSecretsManager(db.secret!, 'username'),
          DB_PASSWORD: ecs.Secret.fromSecretsManager(db.secret!, 'password'),
          DB_NAME: ecs.Secret.fromSecretsManager(db.secret!, 'dbname'),
        },
      },
      healthCheckGracePeriod: Duration.seconds(60),
      // Without this, a task that can't come up healthy makes CloudFormation
      // retry for up to 3 hours before giving up (hit this once already,
      // wasted 3 hours finding out) instead of failing fast so the real
      // stopped-task reason can actually be read before rollback tears
      // everything down.
      circuitBreaker: { enable: true, rollback: true },
    });
    db.connections.allowDefaultPortFrom(api.service, 'Fargate tasks read/write Postgres');
    api.targetGroup.configureHealthCheck({ path: '/healthz', healthyHttpCodes: '200-299' });

    // ---------------------------------------------------------------------
    // Frontend — Vite SPA (`npm run build:deck` -> dist/) on S3 behind
    // CloudFront with an Origin Access Control (no public S3 bucket).
    // ---------------------------------------------------------------------
    const siteBucket = new s3.Bucket(this, 'FrontendBucketV2', {
      // No explicit bucketName: a fixed name collides with the orphan RETAIN
      // leaves behind on a rolled-back deploy (hit this once already). CDK's
      // auto-generated name is deterministic per construct path, so a failed
      // deploy leaves an orphan that then collides again on every retry —
      // renamed the construct id (FrontendBucket -> FrontendBucketV2) to get
      // a fresh name past the one that orphaned. Back to RETAIN now that the
      // stack deploys cleanly end-to-end -- a future stack deletion shouldn't
      // take the built frontend assets with it.
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      removalPolicy: RemovalPolicy.RETAIN,
      versioned: true,
    });

    // ---------------------------------------------------------------------
    // WAF — rate-limit + managed rule sets, in front of CloudFront. This is
    // the "throttle agent traffic" layer from the dossier's readiness checklist.
    //
    // HARD CONSTRAINT: a CLOUDFRONT-scope WebACL can only be created in us-east-1,
    // same as the ACM certificate for the CloudFront distribution below. This stack
    // deploys cleanly today because bin/app.ts defaults CDK_DEFAULT_REGION to
    // us-east-1 -- don't change that default (or pass a different --region) without
    // reworking both of these, or the deploy fails outright.
    // ---------------------------------------------------------------------
    const webAcl = new wafv2.CfnWebACL(this, 'DeckWebAcl', {
      scope: 'CLOUDFRONT',
      defaultAction: { allow: {} },
      visibilityConfig: {
        sampledRequestsEnabled: true,
        cloudWatchMetricsEnabled: true,
        metricName: `01deck-${props.envName}-webacl`,
      },
      rules: [
        {
          name: 'RateLimitPerIp',
          priority: 0,
          action: { block: {} },
          statement: {
            rateBasedStatement: { limit: 2000, aggregateKeyType: 'IP' }, // requests / 5 min / IP
          },
          visibilityConfig: {
            sampledRequestsEnabled: true,
            cloudWatchMetricsEnabled: true,
            metricName: 'RateLimitPerIp',
          },
        },
        {
          name: 'AWSManagedCommonRuleSet',
          priority: 1,
          overrideAction: { none: {} },
          statement: { managedRuleGroupStatement: { vendorName: 'AWS', name: 'AWSManagedRulesCommonRuleSet' } },
          visibilityConfig: {
            sampledRequestsEnabled: true,
            cloudWatchMetricsEnabled: true,
            metricName: 'AWSManagedCommonRuleSet',
          },
        },
        {
          name: 'AWSManagedBotControl',
          priority: 2,
          overrideAction: { none: {} },
          statement: { managedRuleGroupStatement: { vendorName: 'AWS', name: 'AWSManagedRulesBotControlRuleSet' } },
          visibilityConfig: {
            sampledRequestsEnabled: true,
            cloudWatchMetricsEnabled: true,
            metricName: 'AWSManagedBotControl',
          },
        },
      ],
    });

    // DNS / cert are optional — off by default so this stack deploys cleanly
    // before the 01ai.ai hosted zone is delegated to this account.
    let certificate: acm.ICertificate | undefined;
    let hostedZone: route53.IHostedZone | undefined;
    if (props.enableDns) {
      hostedZone = route53.HostedZone.fromLookup(this, 'Zone', { domainName: props.hostedZoneName });
      certificate = new acm.Certificate(this, 'SiteCertificate', {
        domainName: props.domainName,
        validation: acm.CertificateValidation.fromDns(hostedZone),
      });
    }

    // Custom security headers rather than relying on a specific AWS-managed
    // policy id — matches what BETA_DEPLOYMENT_CHECKLIST.md already asked for
    // at the edge (HSTS, nosniff, referrer policy, locked-down permissions).
    const securityHeadersPolicy = new cloudfront.ResponseHeadersPolicy(this, 'SecurityHeaders', {
      responseHeadersPolicyName: `01deck-${props.envName}-security-headers`,
      securityHeadersBehavior: {
        strictTransportSecurity: {
          accessControlMaxAge: Duration.days(365),
          includeSubdomains: true,
          override: true,
        },
        contentTypeOptions: { override: true },
        referrerPolicy: {
          referrerPolicy: cloudfront.HeadersReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN,
          override: true,
        },
      },
      customHeadersBehavior: {
        customHeaders: [
          { header: 'Permissions-Policy', value: 'microphone=(), camera=(), geolocation=()', override: true },
        ],
      },
    });

    const distribution = new cloudfront.Distribution(this, 'FrontendDistribution', {
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(siteBucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
        responseHeadersPolicy: securityHeadersPolicy,
      },
      additionalBehaviors: {
        // /api/* on the same domain proxies to the ALB, matching the
        // single-domain topology BETA_DEPLOYMENT_CHECKLIST.md calls out as preferred.
        '/api/*': {
          origin: new origins.LoadBalancerV2Origin(api.loadBalancer, {
            protocolPolicy: cloudfront.OriginProtocolPolicy.HTTP_ONLY, // ALB terminates TLS separately if you add an ACM cert to it later
          }),
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
          originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
          allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
        },
      },
      defaultRootObject: 'index.html',
      errorResponses: [
        // Vite/React Router SPA fallback — same rewrite vercel.json already does.
        { httpStatus: 403, responseHttpStatus: 200, responsePagePath: '/index.html', ttl: Duration.seconds(0) },
        { httpStatus: 404, responseHttpStatus: 200, responsePagePath: '/index.html', ttl: Duration.seconds(0) },
      ],
      webAclId: webAcl.attrArn,
      domainNames: props.enableDns ? [props.domainName] : undefined,
      certificate,
    });

    if (props.enableDns && hostedZone) {
      new route53.ARecord(this, 'DeckAliasRecord', {
        zone: hostedZone,
        recordName: props.domainName,
        target: route53.RecordTarget.fromAlias(new route53targets.CloudFrontTarget(distribution)),
      });
    }

    // 01Evolve's app/api/app.py wires TrustedHostMiddleware(allowed_hosts=...) straight
    // to 01DECK_ALLOWED_HOSTS, and Starlette rejects any request whose Host header isn't
    // in that list with a 400 -- BEFORE the route even runs. This needs BOTH:
    //  - the ALB's own DNS name, which the ECS target group health check hits directly
    //    (ALB -> container, bypassing CloudFront entirely) at /healthz;
    //  - the real public domain, which is what Host header the container actually sees
    //    on real /api/* traffic. The `ALL_VIEWER_EXCEPT_HOST_HEADER` origin request
    //    policy on the '/api/*' behavior above was assumed to make CloudFront rewrite Host
    //    to the ALB's own DNS before forwarding — verified live against the deployed
    //    stack that this assumption doesn't hold (every /api/* call 400s with "Invalid
    //    host header"); the public domain has to be allow-listed explicitly instead of
    //    relying on that rewrite. Set here (rather than inline where `api` is constructed
    //    above) because it needs `distribution` to exist first.
    const publicHost = props.enableDns ? props.domainName : distribution.distributionDomainName;
    api.taskDefinition.defaultContainer!.addEnvironment(
      '01DECK_ALLOWED_HOSTS',
      `${api.loadBalancer.loadBalancerDnsName},${publicHost}`,
    );

    // ---------------------------------------------------------------------
    // Outputs
    // ---------------------------------------------------------------------
    new CfnOutput(this, 'FrontendUrl', {
      value: props.enableDns ? `https://${props.domainName}` : `https://${distribution.distributionDomainName}`,
    });
    new CfnOutput(this, 'CloudFrontDomain', { value: distribution.distributionDomainName });
    new CfnOutput(this, 'ApiLoadBalancerDns', { value: api.loadBalancer.loadBalancerDnsName });
    new CfnOutput(this, 'FrontendBucketName', { value: siteBucket.bucketName });
    new CfnOutput(this, 'DatabaseSecretArn', { value: db.secret!.secretArn });
    new CfnOutput(this, 'AppSecretsArn', { value: appSecrets.secretArn });
  }
}
